### ISSUE TITLE
Download additional media

### ISSUE THREAD

**Issue by darvid7** [GeckoDM/GeckoDownloadManager#28]
Some recordings have two side by side screens, at the moment only 1 is downloaded.

**Comment by lorderikir** [comment]
It is possible to use `ffmpeg` to stitch videos together
https://lists.ffmpeg.org/pipermail/ffmpeg-user/2013-June/015662.html

or `fluent-ffmpeg` for node servers

**Comment by imaginebreake** [comment]
Link for a secondary screen recording is described in `lesson.video.media.media.current.secondaryFiles`, the format is quite similar to ones in `primaryFiles`.

1. Maybe a new option of whether to download a secondary screen recording.
2. Read the option in `pageSetup()` and call `port.postMessage(toDownload, downloadHD, downloadSecond);` for twice if `downloadSecond`
3. Get link for secondary in `getDownloadLink` in `background.js`  if `downloadSecond` and check existence.

**Comment by imaginebreake** [comment]
Maybe just download two files, no more processing actual video file.

**Comment by ericjiang97** [comment]
@imaginebreake I like that idea, maybe download the 2 options if user selects that option

**Comment by andreyguenov** [comment]
@ericjiang97 @imaginebreake 100% second this issue.

**Comment by CT1994** [comment]
all media that is available is downloaded in this PR
https://github.com/GeckoDM/GeckoDownloadManager/pull/76
@ericjiang97 
@imaginebreake

**Comment by imaginebreake** [comment]
> all media that is available is downloaded in this PR
> #76
> @ericjiang97
> @imaginebreake

Yes, I saw that.
