### ISSUE TITLE
Macquarie Echo360 doesn't function

### ISSUE THREAD

**Issue by poketama** [GeckoDM/GeckoDownloadManager#38]
Fresh public chrome build install, latest GeckoDM install from chrome app store. Echo360 is run through iLearn and not Blackboard.

Files appear in list but do not start download when button pressed.

**Comment by lorderikir** [comment]
Hey @poketama 

Thanks for submitting an issue!

Can you please advise us if Macquarie Uni is running the cloud version of Echo360 (https://echo360.org.au) or not

**Comment by poketama** [comment]
I am unsure how to get the version details  but here is some screenshots. Echo360 is not run in a desktop application but entirely on that website you linked.

![image](https://user-images.githubusercontent.com/33590976/32711377-bb82b19e-c892-11e7-9e8a-01ad6c73a0e5.png)
![image](https://user-images.githubusercontent.com/33590976/32711386-c6b747be-c892-11e7-9ef2-222b5967e0db.png)
![image](https://user-images.githubusercontent.com/33590976/32711413-e09f96ae-c892-11e7-8d04-be7dde9e89db.png)

**Comment by lorderikir** [comment]
Hey @poketama, to help us debug your problem please do the following:
1. Open the Class view
![screen shot 2017-11-14 at 9 50 53 am](https://user-images.githubusercontent.com/5687681/32753536-5157fb78-c921-11e7-9a7c-d05091d3e972.png)
2. Click on the geckoDM Extension Icon
![screen shot 2017-11-14 at 9 51 17 am](https://user-images.githubusercontent.com/5687681/32753547-5ef3118c-c921-11e7-8cba-87b27e926318.png)
3. Right click on the extension and click `Inspect`, this will open up developer tools in a new window.  And open the console tab
![screen shot 2017-11-14 at 9 52 00 am](https://user-images.githubusercontent.com/5687681/32753579-83af7f38-c921-11e7-916e-44185892ccb4.png)
4. Then proceed downloading and submit a screenshot of messages
For example, mine shows
![screen shot 2017-11-14 at 9 52 59 am](https://user-images.githubusercontent.com/5687681/32753601-a17a173a-c921-11e7-98f4-534caacdd478.png)

**Comment by poketama** [comment]
Here is the log after trying to press the download button and refreshing the list a few times. When the download button is pressed the list disappears and nothing happens. Cheers

![image](https://user-images.githubusercontent.com/33590976/32762763-6d2e9ee6-c94f-11e7-9ab8-5c92c91e66cc.png)

**Comment by lorderikir** [comment]
@callistusystan can you take a look at this.

I have a feeling that your Regex Mapping is ruining the downloads

**Comment by andrewjbennett** [comment]
I'm having the same issue with UNSW Echo360.

The list of lectures loads fine, and everything works as far as I can tell in popup.js -- it gets to this part, `toDownload` has the correct contents, but from there nothing happens.

```
      const port = chrome.runtime.connect();
      port.postMessage(toDownload, downloadHD);
      downloadButton.disabled = true;
      $("#lectureSelect").empty();
      mediaLessons = undefined;
```

 (I'm not sure how to further debug the chrome.runtime stuff)

![screenshot from 2018-05-24 00-16-05](https://user-images.githubusercontent.com/864138/40430208-fb4c19f0-5ee7-11e8-9472-4473e4789af1.png)

**Comment by andrewjbennett** [comment]
Okay, I figured out how to look at what the background js is doing.

It seems to download the file, but... doesn't quite get there?

![image](https://user-images.githubusercontent.com/864138/40430640-eb500ef2-5ee8-11e8-996e-a8d3e027626d.png)

There's no file with that name in that location (`/home/andrew/Downloads/` is where downloads should end up, there's nothing called `hd1.mp4` or `hd1 (1).mp4` etc)

**Comment by lorderikir** [comment]
Hey Andrew, we're pushing out an update later today. We'll get you to test it if that's alright

**Comment by andrewjbennett** [comment]
Sure, I'd be happy to, just let me know when it's ready.

>

**Comment by lorderikir** [comment]
Update was pushed out this morning, and should be rolled out across all devices. Version number is: v0.3.0

**Comment by andrewjbennett** [comment]
I have v0.3.5 -- do I somehow have the wrong version? (I got it via the link on your github readme page)

![image](https://user-images.githubusercontent.com/864138/40467470-69a67834-5f6d-11e8-9169-60647e8b297f.png)

Unfortunately it still doesn't seem to work (different errors this time though!)

![image](https://user-images.githubusercontent.com/864138/40467659-16fe18fc-5f6e-11e8-917a-9c33960ffd2b.png)

**Comment by andrewjbennett** [comment]
For what it's worth, if I change the `getUnitCode` function to split on space rather than underscore, it works perfectly (yay!)

So maybe get the function to detect spaces and split on those rather than underscores, if the string has spaces not underscores? *shrug*

**Comment by lorderikir** [comment]
Hmmmm..... We might change some code around then.... Thanks for the help, we might push another update out over the next few days

**Comment by lorderikir** [comment]
`v0.3.7` patches for missing regex patterns
