### ISSUE TITLE
Bug. missing brackets

### ISSUE THREAD

**Issue by theya222** [GeckoDM/GeckoDownloadManager#43]
https://github.com/GeckoDM/GeckoDownloadManager/blob/d989d894680469fa0aea1ef8376584d12115d0a5/app/src/popup.js#L35

app doesnt work for me. unexpected identifier on line 35 is the only error in console.
seems to be missing brackets around if statement condition.

**Comment by lorderikir** [comment]
Thanks for submitting the issue!

**Comment by lorderikir** [comment]
We'll be deploying a fix soon - under v0.3.8.

**Comment by lorderikir** [comment]
Fix has launched in the Chrome App Store...It will up to an hour for all users to receive the update.

**Comment by lorderikir** [comment]
v0.3.8 has launched! 🚀 Should be fixed. Feel free to reopen this issue if its still not working. (or open another ticket for another related issue)

**Comment by darvid7** [comment]
big sorry, ty for picking that up
