### ISSUE TITLE
Adding US support

### ISSUE THREAD

**Issue by brav93** [GeckoDM/GeckoDownloadManager#46]
I am a student at Purdue University and we use Echo360 Lecture capture system. We have several classes that are being recorded and I wanted to download them in order to view them when offline. I was wondering if you guys were planning to ever add support for US institutions.

**Comment by lorderikir** [comment]
@brav93 can U please tell us the domain (something that looks like `echo360.org.au` or `echo360.org.uk` and we'll see if we can sort it out.
