### ISSUE TITLE
Downloading UNSW Echo360 videos still doesn't work

### ISSUE THREAD

**Issue by andrewjbennett** [GeckoDM/GeckoDownloadManager#48]
This was discussed in #38, and "fixed" in #42.

However, #42 only fixes the front-end and not the back-end, so although the correct unit codes now appear in the interface, the download still fails.

I've written a fix for this in #47 (having not seen #42 and just assuming that it somehow didn't get fixed), but perhaps a better approach would be to have just one function for getUnitCode and call that from both places. [I don't know JavaScript well enough to know how to do that]

**Comment by lorderikir** [comment]
Closing issue as this was fixed in #47
