### ISSUE TITLE
Addition for US schools

### ISSUE THREAD

**Issue by ZRah** [GeckoDM/GeckoDownloadManager#50]
I see that the extension works for AU schools, or institutions that have the "echo360.org.au/XXX" URL. Would it be possible to include US schools that use Echo360 Cloud? Would GeckoDM be able to recognize "echo360.org/XXX" (just removed the ".au" portion) for video downloads? If so this would be extremely helpful in helping us American students out. Stony Brook University uses the newer cloud version that appears to be in line with the version that Monash uses. Here is a sample link for a class showing all of the available lectures, perhaps it will help if you so choose to update the extension.

 https://echo360.org/section/bcf054c2-96b3-4377-a6ee-e72ad90d15ae/home

**Comment by Nisreen0** [comment]
This would be great if you could also make it work for org.uk links so it can work for UK universities too!

**Comment by lorderikir** [comment]
Hi @Nisreen0, we added support for the UK region in earlier update. If you are having issues please open a new [Bug report in the issue](https://github.com/GeckoDM/GeckoDownloadManager/issues/new?template=bug_report.md)
