### ISSUE TITLE
Download does not occur

### ISSUE THREAD

**Issue by Nisreen0** [GeckoDM/GeckoDownloadManager#52]
After adding the extension and loading the lectures on the current page, I click to download a lecture and no download occurs. The extension window closes and that’s pretty much it.

 - OS: Microsoft Windows 10
 - Browser: Chrome 67

**Comment by lorderikir** [comment]
Hi @Nisreen0, can you please follow the following steps and show us the logs (https://github.com/GeckoDM/GeckoDownloadManager/issues/38#issuecomment-344086706)

**Comment by Nisreen0** [comment]
It looks like the same thing is happening to me as shown in that issue report[](url)
![capture](https://user-images.githubusercontent.com/32618504/41652089-18dcd606-747a-11e8-8f29-bcac36353e2c.PNG)

**Comment by lorderikir** [comment]
Ok, So it would seem that our Regex parser isn't accounting for all edge cases. We'll see if we can get a PR in and update our app

**Comment by lorderikir** [comment]
Hey @Nisreen0 can u show us the data array please

**Comment by Nisreen0** [comment]
Hope these screenshots are okay, not sure what exactly you wanted to see within the data array

![capture](https://user-images.githubusercontent.com/32618504/41854538-606c472e-7888-11e8-9703-6eb6909ade05.PNG)

![capture 1](https://user-images.githubusercontent.com/32618504/41854540-608909e0-7888-11e8-9748-3297915883c2.PNG)

**Comment by lorderikir** [comment]
Hi @Nisreen0 can you confirm which Institution you go to?
