### ISSUE TITLE
Add UoN to supported institutions

### ISSUE THREAD

**Issue by imaginebreake** [GeckoDM/GeckoDownloadManager#62]
Works great with University of Nottingham (which uses echo360.org.uk), didn't have to change a thing.

Is it possible to detect video in single video page rather than course page?

You saved me a couple of hours worth of coding. Thanks 👍

**Comment by ericjiang97** [comment]
Hi @imaginebreake 

Thanks for confirming that its working for you!

It is possible, as most of our devs have finished uni, we don't have access to echo360, feel free to fork this repository and submit a Pull request.
