### ISSUE TITLE
Folders prevent Gecko from detecting any videos

### ISSUE THREAD

**Issue by sethb3744** [GeckoDM/GeckoDownloadManager#72]
I've noticed that whenever a class has a folder within a set of lectures, Gecko is unable to "Load lectures on page", meaning that when I click that button, none of the lectures on the page get listed under the "Select lecture(s) to download" table.

In case you're not sure what I mean by a "folder," the first two sections below are both examples of a folder, whereas the third row is a video that's just in the main class list.

<img width="1060" alt="Screen Shot 2020-04-03 at 12 15 09 PM" src="https://user-images.githubusercontent.com/10657968/78382386-c77a7880-75a4-11ea-81cc-a2ce32e491d9.png">

I'm pretty certain that the problem only occurs when there is a folder. I tried to load lectures on 10 different classes, 4 of which had folders. It always worked for the classes that didn't have any folders and never worked for the classes that did have folders.

Please let me know if you need anything else from me. Thanks!

**Comment by ericjiang97** [comment]
Hi @sethb3744,

Thanks for submitting an issue! Is it possible to send us the Chrome extensions logs?

You can view how to access the logs [here](https://github.com/GeckoDM/GeckoDownloadManager/issues/38#issuecomment-344086706)

Thanks

**Comment by sethb3744** [comment]
<img width="634" alt="Screen Shot 2020-04-04 at 12 17 57 AM" src="https://user-images.githubusercontent.com/10657968/78418408-ca5b8480-7609-11ea-87a8-53322bda7be8.png">

**Comment by sethb3744** [comment]
Also, for what it's worth, I don't currently need any of the videos that are in folders, so they can be completely ignored if you have trouble including those in the download list. Thanks again!

**Comment by ericjiang97** [comment]
Can you expanded the object that days `Object `?

**Comment by sethb3744** [comment]
<img width="640" alt="Screen Shot 2020-04-04 at 5 41 14 AM" src="https://user-images.githubusercontent.com/10657968/78423797-e7f31300-7636-11ea-8649-19c0dbf3945f.png">

**Comment by sethb3744** [comment]
<img width="637" alt="Screen Shot 2020-04-04 at 5 42 10 AM" src="https://user-images.githubusercontent.com/10657968/78423809-0822d200-7637-11ea-9a16-e801fa5c0439.png">

**Comment by sethb3744** [comment]
Hi, I wanted to check in to see if you need any more information. Totally cool if you're busy, but I can give more screenshots or info if you need it.

**Comment by hugobene** [comment]
Hello, is there a solution?
I really have to download the lectures from my university because the exam is getting closer.

Link to my lectures: https://echo360.org.uk/section/6ebce753-ab28-49b7-85c0-ed5979e3be01/home

If someone could help me please.
Thanks in advance

**Comment by CT1994** [comment]
@hugobene 
@sethb3744 
@imaginebreake 

that was been resolved in the merge above

**Comment by sethb3744** [comment]
Amazing! I just tried it out and it worked on my end. Is there any way to donate?

**Comment by ericjiang97** [comment]
Thanks for confirming that it's been fixed 😊
