### ISSUE TITLE
Lectures don't load by pushing the button

### ISSUE THREAD

**Issue by Bumbali** [GeckoDM/GeckoDownloadManager#75]
I can't download lectures by using this feature on © 2020 Echo360.

If I push the button "load lectures on page" it is reloading the page, but it doesn't put the videos into the window of gecko. Only the Download-button is green then. This happens in every single lecture I have.

Before pushing the button:
![2020-06-17](https://user-images.githubusercontent.com/67063498/84916275-29d01900-b0be-11ea-9fcf-828e33fb2fd4.png)
After pushing the button:
![2020-06-17 (1)](https://user-images.githubusercontent.com/67063498/84916260-23da3800-b0be-11ea-9d12-5824b1eb96f2.png)

**Desktop (please complete the following information):**
 - Microsoft, Laptop: Medion
 - Google Chrome
 - Chrome Version 83.0.4103.106

**Additional context**
I also turned off my AdBlock, but it doesn't change anything. Is there some configuration I have to make or something like that?
My university "Paris-Lodron University Salzburg" also uploaded a new version of "Blackboard" this weekend. May it has a connection?

**Comment by Bubb1eTea** [comment]
Hi, can confirm as a student that is still study at Monash I'm getting the same problem as well

**Comment by ericjiang97** [comment]
Hi all,

Unfortunately many members of team have completed uni and hence lost access to echo360, however we are happy to review any pull requests into this app.

**Comment by TerryF003** [comment]
Same issue. Videos aren't being detected

**Comment by ericjiang97** [comment]
Hi @TerryF003 ,

Thanks for confirming this issue - Unfortunately many members of our team have completed uni and hence lost access to echo360, however we are happy to review any pull requests into this app.

**Comment by mtezzo** [comment]
It appears that echo360 has changed the structure of the JSON in the "syllabus" which has caused this plugin to break.  The new version lacks the keys lesson.hasAvailableVideo and lesson.video.  See screenshot from chrome inspector.
![2020-06-22_17-44-14](https://user-images.githubusercontent.com/1561895/85338667-b9a40780-b4b0-11ea-8eed-93878b3d58c6.png)

**Comment by ericjiang97** [comment]
Hi @mtezzo ,

Thanks for confirming this issue - Unfortunately many core and original of members our team have completed uni and hence lost access to echo360, however we are happy to review any pull requests into this app.

**Comment by imaginebreake** [comment]
Hello, would you plz help me confirm is there still video link in syllabus?

________________________________
发件人: Michael Ezzo <notifications@github.com>
发送时间: Tuesday, June 23, 2020 5:50:21 AM
收件人: GeckoDM/GeckoDownloadManager <GeckoDownloadManager@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [GeckoDM/GeckoDownloadManager] Lectures don't load by pushing the button (#75)


It appears that echo360 has changed the structure of the JSON in the "syllabus" which has caused this plugin to break. The new version lacks the keys lesson.hasAvailableVideo and lesson.video. See screenshot from chrome inspector.
[2020-06-22_17-44-14]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1561895%2F85338667-b9a40780-b4b0-11ea-8eed-93878b3d58c6.png&data=02%7C01%7C%7Ca0598b48f0e441df15bb08d816f6436a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637284594226053307&sdata=4C%2BdTKet2bsEWAr9dreQnnFD2f%2FCddL996ECkETIhSE%3D&reserved=0>

―

**Comment by mtezzo** [comment]
It's been completely removed.  Here's a sample of the JSON (I trimmed it down to just a single object in the data array for brevity and sanitized the values for public posting, but kept all the keys).  It seems that echo360 completely removed all the S3 Urls which were previously embedded in the syllabus.  I've not been able to come up with a way to reconstruct them.

```json
{
   "status":"ok",
   "message":"",
   "data":[
      {
         "lesson":{
            "lesson":{
               "id":"G_66666666-4444-5555-6666-888888888888_22222222-3333-3333-4444-555555555555_1999-01-01T08:00:00.000_1999-01-01T09:00:00.000",
               "institutionId":"55555555-2222-3333-4444-999999999999",
               "sectionId":"22222222-3333-3333-4444-555555555555",
               "captureOccurrenceId":"66666666-4444-5555-6666-888888888888_19990101T1300",
               "name":"Course Code",
               "timing":{
                  "start":"1999-01-07T08:00:00.000",
                  "end":"1999-01-07T09:00:00.000"
               },
               "timeZone":{
                  "id":"US/Eastern",
                  "name":"(-05:00) US/Eastern",
                  "standardOffset":"PT-5H"
               },
               "fromSchedule":false,
               "shouldStreamLive":true,
               "createdAt":"1999-01-01T13:14:23.123Z",
               "updatedAt":"1999-01-01T13:14:23.123Z",
               "displayName":"Course Code",
               "lessonHasName":true
            },
            "medias":[
               {
                  "id":"11111111-2222-3333-4444-555555555555",
                  "mediaType":"Video",
                  "title":"Example Course Name",
                  "isAvailable":true,
                  "isHiddenDueToCaptions":false,
                  "isRead":true,
                  "isScheduled":false,
                  "isProcessing":false,
                  "isFailed":false,
                  "isPreliminary":false
               }
            ],
            "userSectionRole":"Instructor",
            "captureStartedAt":"1999-01-01T08:00:00.000",
            "captureEndedAt":"1999-01-01T08:00:00.000",
            "questionCount":0,
            "isScheduled":false,
            "hasContent":true,
            "hasVideo":true,
            "hasVideoHiddenDueToCaptions":false,
            "hasSlideDeck":false,
            "isLive":false,
            "isPast":true,
            "isFuture":false,
            "startTimeUTC":"1999-01-01T13:00:00.000Z",
            "endTimeUTC":"1999-01-01T14:00:00.000Z"
         },
         "type":"SyllabusLessonType"
      }
   ]
}
```

**Comment by imaginebreake** [comment]
Well, this project generally relies on that link.

________________________________
发件人: Michael Ezzo <notifications@github.com>
发送时间: Saturday, June 27, 2020 8:14:05 PM
收件人: GeckoDM/GeckoDownloadManager <GeckoDownloadManager@noreply.github.com>
抄送: ImagineBreaker <breakertt@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [GeckoDM/GeckoDownloadManager] Lectures don't load by pushing the button (#75)


It's been completely removed. Here's a sample of the JSON (I trimmed it down to just a single object in the data array for brevity and sanitized the values for public posting, but kept all the keys). It seems that echo360 completely removed all the S3 Urls which were previously embedded in the syllabus. I've not been able to come up with a way to reconstruct them.

{
   "status":"ok",
   "message":"",
   "data":[
      {
         "lesson":{
            "lesson":{
               "id":"G_66666666-4444-5555-6666-888888888888_22222222-3333-3333-4444-555555555555_1999-01-01T08:00:00.000_1999-01-01T09:00:00.000",
               "institutionId":"55555555-2222-3333-4444-999999999999",
               "sectionId":"22222222-3333-3333-4444-555555555555",
               "captureOccurrenceId":"66666666-4444-5555-6666-888888888888_19990101T1300",
               "name":"Course Code",
               "timing":{
                  "start":"1999-01-07T08:00:00.000",
                  "end":"1999-01-07T09:00:00.000"
               },
               "timeZone":{
                  "id":"US/Eastern",
                  "name":"(-05:00) US/Eastern",
                  "standardOffset":"PT-5H"
               },
               "fromSchedule":false,
               "shouldStreamLive":true,
               "createdAt":"1999-01-01T13:14:23.123Z",
               "updatedAt":"1999-01-01T13:14:23.123Z",
               "displayName":"Course Code",
               "lessonHasName":true
            },
            "medias":[
               {
                  "id":"11111111-2222-3333-4444-555555555555",
                  "mediaType":"Video",
                  "title":"Example Course Name",
                  "isAvailable":true,
                  "isHiddenDueToCaptions":false,
                  "isRead":true,
                  "isScheduled":false,
                  "isProcessing":false,
                  "isFailed":false,
                  "isPreliminary":false
               }
            ],
            "userSectionRole":"Instructor",
            "captureStartedAt":"1999-01-01T08:00:00.000",
            "captureEndedAt":"1999-01-01T08:00:00.000",
            "questionCount":0,
            "isScheduled":false,
            "hasContent":true,
            "hasVideo":true,
            "hasVideoHiddenDueToCaptions":false,
            "hasSlideDeck":false,
            "isLive":false,
            "isPast":true,
            "isFuture":false,
            "startTimeUTC":"1999-01-01T13:00:00.000Z",
            "endTimeUTC":"1999-01-01T14:00:00.000Z"
         },
         "type":"SyllabusLessonType"
      }
   ]
}

―

**Comment by imaginebreake** [comment]
> It's been completely removed. Here's a sample of the JSON (I trimmed it down to just a single object in the data array for brevity and sanitized the values for public posting, but kept all the keys). It seems that echo360 completely removed all the S3 Urls which were previously embedded in the syllabus. I've not been able to come up with a way to reconstruct them.
> 
> ```json
> {
>    "status":"ok",
>    "message":"",
>    "data":[
>       {
>          "lesson":{
>             "lesson":{
>                "id":"G_66666666-4444-5555-6666-888888888888_22222222-3333-3333-4444-555555555555_1999-01-01T08:00:00.000_1999-01-01T09:00:00.000",
>                "institutionId":"55555555-2222-3333-4444-999999999999",
>                "sectionId":"22222222-3333-3333-4444-555555555555",
>                "captureOccurrenceId":"66666666-4444-5555-6666-888888888888_19990101T1300",
>                "name":"Course Code",
>                "timing":{
>                   "start":"1999-01-07T08:00:00.000",
>                   "end":"1999-01-07T09:00:00.000"
>                },
>                "timeZone":{
>                   "id":"US/Eastern",
>                   "name":"(-05:00) US/Eastern",
>                   "standardOffset":"PT-5H"
>                },
>                "fromSchedule":false,
>                "shouldStreamLive":true,
>                "createdAt":"1999-01-01T13:14:23.123Z",
>                "updatedAt":"1999-01-01T13:14:23.123Z",
>                "displayName":"Course Code",
>                "lessonHasName":true
>             },
>             "medias":[
>                {
>                   "id":"11111111-2222-3333-4444-555555555555",
>                   "mediaType":"Video",
>                   "title":"Example Course Name",
>                   "isAvailable":true,
>                   "isHiddenDueToCaptions":false,
>                   "isRead":true,
>                   "isScheduled":false,
>                   "isProcessing":false,
>                   "isFailed":false,
>                   "isPreliminary":false
>                }
>             ],
>             "userSectionRole":"Instructor",
>             "captureStartedAt":"1999-01-01T08:00:00.000",
>             "captureEndedAt":"1999-01-01T08:00:00.000",
>             "questionCount":0,
>             "isScheduled":false,
>             "hasContent":true,
>             "hasVideo":true,
>             "hasVideoHiddenDueToCaptions":false,
>             "hasSlideDeck":false,
>             "isLive":false,
>             "isPast":true,
>             "isFuture":false,
>             "startTimeUTC":"1999-01-01T13:00:00.000Z",
>             "endTimeUTC":"1999-01-01T14:00:00.000Z"
>          },
>          "type":"SyllabusLessonType"
>       }
>    ]
> }
> ```

This project relies heavily on that lin in "Syllabus", I am afraid I am unable to fix this issue.

**Comment by dalyIsaac** [comment]
I agree that echo360 doesn't seem to be using `.mp4` files anymore, at least on the website. If you look at the contents of the network tab, there are requests to `.m3u8` and `.m4s` files.

The `.m3u8` files are playlist files for HLS streaming files, which are what the `.m4s` files are. For more about HLS, you can read up [Setting up adaptive streaming media sources](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Setting_up_adaptive_streaming_media_sources) on MDN. 

The actual contents of the `.m4s` requests seem to be requesting a new `Content-Range` header for each request.

![image](https://user-images.githubusercontent.com/17995621/86229220-844f9600-bbe3-11ea-83cb-b210e4afce64.png)

I haven't had any luck trying to download the videos using the `.m3u8` playlists, so I've had a tiny wee poke around the source code. All the relevant code has been put through Webpack, and can be found in classroomApp.react-bundle.js`. 

There's 74 files bundled:

```
./src/config.js
./src/controller/abr-controller.js
./src/controller/audio-stream-controller.js
./src/controller/audio-track-controller.js
./src/controller/base-stream-controller.js
./src/controller/buffer-controller.js
./src/controller/cap-level-controller.js
./src/controller/eme-controller.js
./src/controller/fps-controller.js
./src/controller/fragment-finders.js
./src/controller/fragment-tracker.js
./src/controller/gap-controller.js
./src/controller/id3-track-controller.js
./src/controller/level-controller.js
./src/controller/level-helper.js
./src/controller/stream-controller.js
./src/controller/subtitle-stream-controller.js
./src/controller/subtitle-track-controller.js
./src/controller/timeline-controller.js
./src/crypt/aes-crypto.js
./src/crypt/aes-decryptor.js
./src/crypt/decrypter.js
./src/crypt/fast-aes-key.js
./src/demux/aacdemuxer.js
./src/demux/adts.js
./src/demux/demuxer-inline.js
./src/demux/demuxer-worker.js
./src/demux/demuxer.js
./src/demux/exp-golomb.js
./src/demux/id3.js
./src/demux/mp3demuxer.js
./src/demux/mp4demuxer.js
./src/demux/mpegaudio.js
./src/demux/sample-aes.js
./src/demux/tsdemuxer.js
./src/errors.js
./src/event-handler.js
./src/events.js
./src/hls.js
./src/is-supported.js
./src/loader/fragment-loader.js
./src/loader/fragment.js
./src/loader/key-loader.js
./src/loader/level-key.js
./src/loader/level.js
./src/loader/m3u8-parser.js
./src/loader/playlist-loader.js
./src/observer.js
./src/polyfills/number.js
./src/remux/aac-helper.js
./src/remux/mp4-generator.js
./src/remux/mp4-remuxer.js
./src/remux/passthrough-remuxer.js
./src/task-loop.js
./src/utils/attr-list.js
./src/utils/binary-search.js
./src/utils/buffer-helper.js
./src/utils/cea-608-parser.js
./src/utils/codecs.js
./src/utils/cues.js
./src/utils/discontinuities.js
./src/utils/ewma-bandwidth-estimator.js
./src/utils/ewma.js
./src/utils/get-self-scope.js
./src/utils/logger.js
./src/utils/mediakeys-helper.js
./src/utils/mediasource-helper.js
./src/utils/output-filter.js
./src/utils/texttrack-utils.js
./src/utils/time-ranges.js
./src/utils/vttcue.js
./src/utils/vttparser.js
./src/utils/webvtt-parser.js
./src/utils/xhr-loader.js
```

As you can see, there's several interesting filenames:

Crypto:

- `./src/crypt/aes-crypto.js`
- `./src/crypt/aes-decryptor.js`
- `./src/crypt/decrypter.js`
- `./src/crypt/fast-aes-key.js`
- `./src/demux/sample-aes.js`

Media:

- `./src/controller/audio-stream-controller.js`
- `./src/controller/audio-track-controller.js`
- `./src/controller/base-stream-controller.js`
- `./src/controller/buffer-controller.js`
- `./src/demux/mp3demuxer.js`
- `./src/demux/mp4demuxer.js`
- `./src/demux/mpegaudio.js`
- `./src/hls.js`
- `./src/loader/m3u8-parser.js`
- `./src/loader/playlist-loader.js`
- `./src/remux/mp4-generator.js`
- `./src/remux/mp4-remuxer.js`
- `./src/utils/codecs.js`
- `./src/utils/mediasource-helper.js`

I don't really want to go through all the minified code, as especially after prettifying it there's 197k lines. If someone wants to have a look, I suppose this is a good starting point.

I guess the easiest thing to do would be to ask your lecturers to enable downloading...

**Comment by Bumbali** [comment]
Hey there!
Thank you for all the answers! I am afraid that I don't really understand the programing-language.

The thing is that my lecturers told us that it should be possible to download them, but there is no button for it anywhere. So they must did not enable it or forgot about it or something... or echo360 just doesn't like me xD

But in the end there should be a way to download them and my question now is if there is any way to program something, so that I can download them for myself or isn't it possible? Or would you have to "hack" the echo360?

**Comment by ericjiang97** [comment]
> I agree that echo360 doesn't seem to be using `.mp4` files anymore, at least on the website. If you look at the contents of the network tab, there are requests to `.m3u8` and `.m4s` files.
> 
> The `.m3u8` files are playlist files for HLS streaming files, which are what the `.m4s` files are. For more about HLS, you can read up [Setting up adaptive streaming media sources](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Setting_up_adaptive_streaming_media_sources) on MDN. 
> 
> The actual contents of the `.m4s` requests seem to be requesting a new `Content-Range` header for each request.
> 
> ![image](https://user-images.githubusercontent.com/17995621/86229220-844f9600-bbe3-11ea-83cb-b210e4afce64.png)
> 
> I haven't had any luck trying to download the videos using the `.m3u8` playlists, so I've had a tiny wee poke around the source code. All the relevant code has been put through Webpack, and can be found in classroomApp.react-bundle.js`. 
> 
> There's 74 files bundled:
> 
> ```
> ./src/config.js
> ./src/controller/abr-controller.js
> ./src/controller/audio-stream-controller.js
> ./src/controller/audio-track-controller.js
> ./src/controller/base-stream-controller.js
> ./src/controller/buffer-controller.js
> ./src/controller/cap-level-controller.js
> ./src/controller/eme-controller.js
> ./src/controller/fps-controller.js
> ./src/controller/fragment-finders.js
> ./src/controller/fragment-tracker.js
> ./src/controller/gap-controller.js
> ./src/controller/id3-track-controller.js
> ./src/controller/level-controller.js
> ./src/controller/level-helper.js
> ./src/controller/stream-controller.js
> ./src/controller/subtitle-stream-controller.js
> ./src/controller/subtitle-track-controller.js
> ./src/controller/timeline-controller.js
> ./src/crypt/aes-crypto.js
> ./src/crypt/aes-decryptor.js
> ./src/crypt/decrypter.js
> ./src/crypt/fast-aes-key.js
> ./src/demux/aacdemuxer.js
> ./src/demux/adts.js
> ./src/demux/demuxer-inline.js
> ./src/demux/demuxer-worker.js
> ./src/demux/demuxer.js
> ./src/demux/exp-golomb.js
> ./src/demux/id3.js
> ./src/demux/mp3demuxer.js
> ./src/demux/mp4demuxer.js
> ./src/demux/mpegaudio.js
> ./src/demux/sample-aes.js
> ./src/demux/tsdemuxer.js
> ./src/errors.js
> ./src/event-handler.js
> ./src/events.js
> ./src/hls.js
> ./src/is-supported.js
> ./src/loader/fragment-loader.js
> ./src/loader/fragment.js
> ./src/loader/key-loader.js
> ./src/loader/level-key.js
> ./src/loader/level.js
> ./src/loader/m3u8-parser.js
> ./src/loader/playlist-loader.js
> ./src/observer.js
> ./src/polyfills/number.js
> ./src/remux/aac-helper.js
> ./src/remux/mp4-generator.js
> ./src/remux/mp4-remuxer.js
> ./src/remux/passthrough-remuxer.js
> ./src/task-loop.js
> ./src/utils/attr-list.js
> ./src/utils/binary-search.js
> ./src/utils/buffer-helper.js
> ./src/utils/cea-608-parser.js
> ./src/utils/codecs.js
> ./src/utils/cues.js
> ./src/utils/discontinuities.js
> ./src/utils/ewma-bandwidth-estimator.js
> ./src/utils/ewma.js
> ./src/utils/get-self-scope.js
> ./src/utils/logger.js
> ./src/utils/mediakeys-helper.js
> ./src/utils/mediasource-helper.js
> ./src/utils/output-filter.js
> ./src/utils/texttrack-utils.js
> ./src/utils/time-ranges.js
> ./src/utils/vttcue.js
> ./src/utils/vttparser.js
> ./src/utils/webvtt-parser.js
> ./src/utils/xhr-loader.js
> ```
> 
> As you can see, there's several interesting filenames:
> 
> Crypto:
> 
> - `./src/crypt/aes-crypto.js`
> - `./src/crypt/aes-decryptor.js`
> - `./src/crypt/decrypter.js`
> - `./src/crypt/fast-aes-key.js`
> - `./src/demux/sample-aes.js`
> 
> Media:
> 
> - `./src/controller/audio-stream-controller.js`
> - `./src/controller/audio-track-controller.js`
> - `./src/controller/base-stream-controller.js`
> - `./src/controller/buffer-controller.js`
> - `./src/demux/mp3demuxer.js`
> - `./src/demux/mp4demuxer.js`
> - `./src/demux/mpegaudio.js`
> - `./src/hls.js`
> - `./src/loader/m3u8-parser.js`
> - `./src/loader/playlist-loader.js`
> - `./src/remux/mp4-generator.js`
> - `./src/remux/mp4-remuxer.js`
> - `./src/utils/codecs.js`
> - `./src/utils/mediasource-helper.js`
> 
> I don't really want to go through all the minified code, as especially after prettifying it there's 197k lines. If someone wants to have a look, I suppose this is a good starting point.
> 
> I guess the easiest thing to do would be to ask your lecturers to enable downloading...
> 

Thanks for the technical details - looks like it doesn't use S3 buckets anymore, the download feature requires access to the S3 buckets.

**Comment by ericjiang97** [comment]
> Hey there!
> Thank you for all the answers! I am afraid that I don't really understand the programing-language.
> 
> The thing is that my lecturers told us that it should be possible to download them, but there is no button for it anywhere. So they must did not enable it or forgot about it or something... or echo360 just doesn't like me xD
> 
> But in the end there should be a way to download them and my question now is if there is any way to program something, so that I can download them for myself or isn't it possible? Or would you have to "hack" the echo360?
> 
> And yes, I know it may be a lot of work, but it would help me in such a great way to get threw my study. Thanks!

Unfortunately, as discussed GeckoDM requires access to the S3 bucket url. I'm not too sure what's changed as I've finished my degree last December. But the logs and network requests provided indicates a major change in how Echo360 manages the download urls now.

**Comment by CT1994** [comment]
ok i have committed a fix for this Echo360 has changed there json data and now server all information within there html files for each page.

if someone can take a look thank you

https://github.com/GeckoDM/GeckoDownloadManager/pull/76

**Comment by dalyIsaac** [comment]
> ok i have committed a fix for this Echo360 has changed there json data and now server all information within there html files for each page.
> 
> if someone can take a look thank you
> 
> #76

That's a good find! Just out of curiosity, where did you find the mp4 URL?

**Comment by imaginebreake** [comment]
> > ok i have committed a fix for this Echo360 has changed there json data and now server all information within there html files for each page.
> > if someone can take a look thank you
> > #76
> 
> That's a good find! Just out of curiosity, where did you find the mp4 URL?

@CT1994 Is there any explicit mp4 URL now? Or it is just guessing from ids?

**Comment by CT1994** [comment]
@imaginebreake 

in background.js getDownloadLink, I request the lesson html page, echo360 have started putting data within the HTML files they generate on serverside to hide video data, i parse this html file grab the data out of this html file then generate the video url

**Comment by imaginebreake** [comment]
> @imaginebreake
> 
> in background.js getDownloadLink, I request the lesson html page, echo360 have started putting data within the HTML files they generate on serverside to hide video data, i parse this html file grab the data out of this html file then generate the video url

@CT1994 I saw that, thanks for your wonderful work!

**Comment by CT1994** [comment]
@imaginebreake 

so the url format is
https://content.{domain}/0000.{institutionId}/{medias[index].id}/{hd{index} or sd{index}}.mp4

the 4 digit above (eg 0000) is impossible to get from any other source of data and most likely generated server side

**Comment by imaginebreake** [comment]
> @imaginebreake
> 
> so the url format is
> [https://content.{domain}/0000.{institutionId}/{medias[index].id}/{hd{index}](https://content.%7Bdomain%7D/0000.%7BinstitutionId%7D/%7Bmedias%5Bindex%5D.id%7D/%7Bhd%7Bindex%7D) or sd{index}}.mp4
> 
> the 4 digit above (eg 0000) is impossible to get from any other source of data and most likely generated server side

So is your code actually detecting URL or generating from your pattern?

**Comment by CT1994** [comment]
@imaginebreake detects and generate the url but did not know the above was a possibility

**Comment by CT1994** [comment]
@imaginebreake can you send me the syllabus json data for that lesson and i can take a look at that

**Comment by imaginebreake** [comment]
> @imaginebreake can you send me the syllabus json data for that lesson and i can take a look at that

Could you please offer me an email address?

**Comment by CT1994** [comment]
or even better can you put a debugger after videoDataObject in background.js #getDownloadLink

**Comment by CT1994** [comment]
@imaginebreake sent a email to your outlook account confirming with my git username
